### ISSUE TITLE
What about ubiquitous forms?

### ISSUE THREAD

**Issue by juepiezhongren** [adamped/Skixam#2]
Hello, Adam.
     I don't think there should be a new platform based upon skiasharp, but i believe that there should be a set of tools for ubiquitous UX. My suggestions are below
     1)UbiGrid, UbiStackPanel, UbiLabel...... Ubis are better than a new platform, because it could be used together with existing forms' api without any change.
     2)For nesting, "solo-ubi", there should only be one renderer just like skixam' idea.
```
<UbiGrid>
    <UbiStackPanel>
        <UbiLabel/>
        <UbiButton/>
        <UbiLabel/>
    </UbiStackPanel>
</UbiGrid>
```
  
    3)For nesting, "non->ubi", renderers should be as many as root-ubis, below there should be 3
```
<Grid>
    <StackPanel>
        <UbiLabel/>
        <UbiButton/>
        <UbiLabel/>
    </StackPanel>
</Grid>
```

     4)For nesting, "ubi-root", there should be 2 renderers,  one skiaView renderer and one other render for nonUbis layout.
```
<UbiGrid>
    <UbiStackPanel>
        <Grid>
           <UbiButton/>
        </Grid>
        <UbiButton/>
        <UbiLabel/>
    </UbiStackPanel>
</UbiGrid>
```

     5)Skia is good, but to decouple it from ubi is better. Skia is only for 2D, other engines should also be given the hook. So, there will be things like this.
```
<UbiGrid Engine="Skia">
    <UbiStackPanel Engine="Urho">
        <Grid>
           <UbiButton/>
        </Grid>
        <UbiButton/>
        <UbiLabel/>
    </UbiStackPanel>
</UbiGrid>
```

**Comment by adamped** [comment]
The point of Skixam was showing that it could all run on SkiaSharp, without any API change in Xamarin.Forms, and have the same look on all platforms. 

SkiaSharp would be more like a sub-platform, that also runs on iOS, Android etc, just on a SkiaSharp canvas.

I'm not sure how an UbiButton would be implemented? Is Ubi another framework I haven't heard of or just the name of a new potential control?

**Comment by juepiezhongren** [comment]
its just a name invented by me. i dont quite understand why ubiButton cant be impled， maybe i didnt get the point

**Comment by adamped** [comment]
Skixam would just use the same Xamarin.Forms Button, then each platform (iOS, UWP, Android, etc), would have a Skia canvas, and it would look the same on every platform. So Skixam is like a sub-platform. It sits on the top, and everything goes through Skia, so it will be identical on every platform. People could just then change what AppFormsDelegate, or FormsAppCompatActivity etc to the new Skia one, keep their entire app exactly the same, and it would just now run on Skia. Hence this approach requires zero changes for Xamarin.Forms developers, and you get the identical look on all platforms :)

**Comment by juepiezhongren** [comment]
i suggest name button in skixam as ubiButton，while the traditional button would coexist with ubi. thats what i mean not a new platform but "tool"，or new api

**Comment by adamped** [comment]
But I didn't want a new button, I just want to define the button as I do currently, but then have it look exactly the same on all platforms. Thats what this solution does. Having a separate button, would result in mixing regular Xamarin.Forms with a Skia Xamarin.Forms and that kind of defeats the purpose. Plus you can already do that if you want to just add a SkiaCanvas to your app, in small sections and write whatever controls you want there. :)

**Comment by juepiezhongren** [comment]
haha，i suggest a progressive-conservatism strategy，make existing skill available，backward compatibility

**Comment by juepiezhongren** [comment]
some controls r good enough，rewrite would be better，but will delay adoption pace.
